### ISSUE TITLE
Faq update?

### ISSUE THREAD

**Issue by seathasky** [redstrate/xivlauncher#18]
![Screen Shot 2022-02-01 at 10 29 56 PM](https://user-images.githubusercontent.com/17598024/152088828-37023813-cb06-4492-ba73-8830c2f7695c.png)

Not sure if you're aware of this, but it's something that has been in the works for a while now:
Interesting to see another project up around the same time we started ours :)

https://www.xivmac.com

**Comment by redstrate** [comment]
Yes I am aware of your project! I commend you for supporting more macOS users :-) I'm sorry to forget about your inclusion, but I'll update the FAQ accordingly!

**Comment by seathasky** [comment]
I more so meant it if you wanted to fork our project to help yours :P

**Comment by seathasky** [comment]
Oh we're also looking for more developers to add to our team, if you're interested!

**Comment by redstrate** [comment]
> Oh we're also looking for more developers to add to our team, if you're interested!

I'll definitely take a look! Unfortunately I'm not playing XIV on my mac as much as I used to (mostly because it's such a subpar experience out of the box) but I do wanna help sometime!
